language: python
python:
    - "2.7"
env:
    - VERSION=v0.0.0.1
    - FLASK_CAT=ShadowCat/FlaskCat
before_install:
    - cd $FLASK_CAT
install: pip install -r requirements.txt
script:
    - git tag $VERSION
    - git push origin --tags
